### ISSUE TITLE
Lock screen does not persist

### ISSUE THREAD

**Issue by hall9989** [ladyrank/joplin-plugin-app-locker#1]
Great plugin, thank you!

I have just noticed that once the lock screen kicks in, simply closing and opening Joplin will get rid of the lock screen. Is it possible to make the lock screen persist after shutting Joplin and re-opening it?

Thank you

**Comment by ladyrank** [comment]
Thanks for your appreciate. I just released new version 1.0.8, it will show in joplin app's plugin list half an hour later. Please try the new version.

If any issue, please leave comments here.
