### ISSUE TITLE
README.md: Include note that end-to-end encryption is not local encryption

### ISSUE THREAD

**Issue by personalizedrefrigerator** [ladyrank/joplin-plugin-app-locker#2]
Currently, `README.md` states

https://github.com/ladyrank/joplin-plugin-app-locker/blob/a8df764ce0c41ebc3fb6d705f30ebf90b70e2255/README.md?plain=1#L7

However, enabling end-to-end encryption does not encrypt data locally &mdash; instead it encrypts data on the server. See [this post on the forum](https://discourse.joplinapp.org/t/are-local-notes-encrypted/10774) and [this entry in the FAQ](https://joplinapp.org/help/faq/#could-there-be-a-password-to-restrict-access-to-joplin) for details.

It might make sense to instead explain that locked notes can still be accessed with this plugin enabled (it's just a bit more difficult).

Thank you for working on this plugin!

**Comment by ladyrank** [comment]
I know it's not local encryption. It's to encrypt your file on cloud. Thanks for your advice.
