### ISSUE TITLE
Is it able to hide the menu?

### ISSUE THREAD

**Issue by auzout** [ladyrank/joplin-plugin-app-locker#3]
Hello,

I use windows10 and when I restart Joplin, I found it's really easy to unlock the software just by click Tools=>Options and then disable the lock plugin. Is it possible to hide the menus when start or is there any work around?

![20231222231604](https://github.com/ladyrank/joplin-plugin-app-locker/assets/11851493/c1c0e52d-1a0f-49d8-89f4-eb0a15f577e8)

**Comment by auzout** [comment]
Will enlarge the white panel resolve this problem?

**Comment by ladyrank** [comment]
Sorry, there is no way to do something to this after I read all of Joplin apis: https://joplinapp.org/api/references/plugin_api/classes/joplin.html .
