### ISSUE TITLE
Not working if someone disable the plugin from Joplin - Preferences - Plugins - app screen locker

### ISSUE THREAD

**Issue by tinymind** [ladyrank/joplin-plugin-app-locker#4]
Someone can easily disable this plugin even if a password is set.

<img width="337" alt="image" src="https://github.com/ladyrank/joplin-plugin-app-locker/assets/6042046/df96d8fa-3692-44e9-b234-3ea9f87b1aec">

**Comment by ladyrank** [comment]
please see this plugin descriptions carefully. this plugin is not to strong protect your note data. It has no ability to do that.
