### ISSUE TITLE
这个加密对于目前的版本来说没有任何作用

### ISSUE THREAD

**Issue by Mr-YW** [ladyrank/joplin-plugin-app-locker#7]
加密后还能点击上面的菜单，可以把所有的笔记导出来，加密设置密码也没有确认输入密码

**Comment by ladyrank** [comment]
> 加密后还能点击上面的菜单，可以把所有的笔记导出来，加密设置密码也没有确认输入密码

这个组件不是用来加密的，谢谢，请仔细阅读使用说明。加密功能 joplin 本身已经提供了。这个插件只是一个简单的屏幕保护功能。

**Comment by Mr-YW** [comment]
你好，我知道是屏幕保护功能，既然是保护功能，但是却能操作菜单的导出，保护就没有了意义，所有的笔记都能被导出看到呢

**Comment by ladyrank** [comment]
> 你好，我知道是屏幕保护功能，既然是保护功能，但是却能操作菜单的导出，保护就没有了意义，所有的笔记都能被导出看到呢

作为joplin的插件屏蔽不了导出。这个插件你可以理解为就是一个简单的防偷窥屏幕或防偷窥笔记内容的插件。

**Comment by ladyrank** [comment]
上面说了，一个插件做不到保护你数据的功能。笔记软件自带了加密，自己设置，导出的也是加密后的，别人解不开。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月8日(周二) 晚上10:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ladyrank/joplin-plugin-app-locker] 这个加密对于目前的版本来说没有任何作用 (Issue #7)




 
你好，我知道是屏幕保护功能，既然是保护功能，但是却能操作菜单的导出，保护就没有了意义，所有的笔记都能被导出看到呢

**Comment by Mr-YW** [comment]
导出是明文呀
